### ISSUE TITLE
Blog post about peerDependencies

### ISSUE THREAD

**Issue by balupton** [balupton/meta#1]
@markdalgleish can you let me know some questions, or areas you specifically want more knowledge about? So that I can address them in a blog post.

[source](https://twitter.com/markdalgleish/status/482055026135678976)

**Comment by markdalgleish** [comment]
I'm mostly interested in what semver ranges plugins should use when specifying peer dependencies, and how optimistic they are. Should they lock down the major version or just specify the minimum supported version?

My concern here is that an update to the major version of the peer dependency might be as relatively harmless as deprecating a feature nobody uses, but this would suddenly invalidate all the plugins which would now potentially be expecting different versions of their host framework for no good reason. Some plugins might break, but maybe only 1% of plugins break.

I imagine, as a framework author, this could scare me into basically never touching the core API. I'd love to hear if there's a way to make peer dependencies worth the hassle.

**Comment by balupton** [comment]
Closing, as it all depends on your requirements.
