### ISSUE TITLE
Refresh website to adjust fulcrum and lever for more recent lifestyle, framework of life, and external occurences and situation

### ISSUE THREAD

**Issue by balupton** [balupton/meta#6]
Hi. I'm Benjamin Arthur Lupton.
    You can call me Ben.
## Impact

Presented 25 times / 6 counties / 4 schools / 10 meetups / 3 conferences / 2000 people

Mentored 3 schools / 50 students 

Ran 5 trainings / 50 patrons / 3 companies / 3 schools

Advised 25 companies / 10 years

Top 20 most active open-sourcer in the world / 4 years

Created Bevry an open-company and community that manages over 255 open-source projects

Initiated the History.js and DocPad projects / used by Microsoft, Adobe, Basecamp, and others.

Initiated the Startup Hostel network / 25 co-work and co-live locations around the world
### Events

Upcoming. Occurred. Trainings. Apperances. Countries.
### Writings

Combined.
### Influences

Projects.
### Presentations

Listing.
### Videos

Youtube.
### Testimonials

Pulled from LinkedIn.
### Reading

Reading. Read.
### Hobbies

Psychology. Money free living. Social activism. Economic reform.
### Visitations

Travel is a big part of my life. If you're a company with a budget, or a rebel with a couch, I'd love to visit you.
### Conferences/Events

Want me to speak about a topic of interest to you at a particular conference? Let me know and I'll happily submit a proposal.
### Trainings/Courses

I run several trainings that can be seen in the events section above, however I can also prepare custom trainings on occasion on-site and off-site. Let me know your ideas and we'll work something out.
### Advisory

Tackling a problem I've already solved? Happy to help. Shoot me an email and we'll work something out.
### Discuss

Currently fascinated by economic reform and social activism, especially in utilising technology and people to equalise and decentralise power distribution. If you're also fascinated by that, or something else that we share in common, happy to chat. Email me.
### Tweet

I enjoy twitter's candidness and accessibility. Tweet me.

**Comment by balupton** [comment]
@Rob-Morris what are your thoughts? The plan here is to adjust my current positioning to be more reflective of my recent values and desires as well as be more selling to the experiences that I'm after.

**Comment by Rob-Morris** [comment]
Yeah, I think it harmonises with where you're at, especially once you've finished fleshing out the detail of the points. I think you have a lot to give in regards to speaking and training and writing in particular, and I'd love to see you able to do more of that.

Putting my commercial "see the world as a company" glasses on for a moment, I'd love the ability to provide some moderate amount of funds to you on a regular basis, and/or to financially back work on certain of your open source projects, in return for the right to commercially market our involvement in that open source project, and that we work with you or that you're available as part of our team.

For instance, we'd love to come to some arrangement that would enable us to say "we support the development of tools such as chainy.js" (etc), or if we're pitching for a project to be able to legitimately claim "Benjamin Lupton is one of our team, here is his bio".

Even just the right to say "Prismatik supports Benjamin Lupton to work on projects including ...", and have that matched with a "Prismatik helps to support my work on projects including..." would be mutually beneficial, I think.

(All first principals of ethics and everybody-benefits should be applied to above thoughts; no commercial arrangements should reduce the benefit of your work for the wider community, be misleading or create perverse incentives)

**Comment by balupton** [comment]
I think the current website still works better than this proposal.
